version: '3.8'

services:
  app:
    build: .
    container_name: go_app
    ports:
      - '8080:8080' # Adjust according to your app's exposed port
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - '5432:5432'
